# See the dedicated "version" documentation section.
version: "2"
linters:
  # See the dedicated "linters" documentation section.
  default: none
  enable:
    - canonicalheader
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - dupl
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - exptostd
    - fatcontext
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - godox
    - gosec
    - gosmopolitan
    - govet
    - iface
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - loggercheck
    - mirror
    - misspell
    - mnd
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nlreturn
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
formatters:
  # See the dedicated "formatters" documentation section.
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
issues:
  fix: true
