version: '3'

tasks:
  install-tools:
    desc: Install necessary buf CLI tool
    cmds:
      - echo "Installing buf CLI..."
      - |
        if ! command -v buf &> /dev/null; then
          go install github.com/bufbuild/buf/cmd/buf@latest
        fi

  proto:
    desc: Generate all proto files using buf
    cmds:
      - echo "Generating proto files with buf..."
      - mkdir -p internal/transport/grpc/pb
      - mkdir -p api/swagger
      - cd ../contracts && buf mod update
      - cd ../contracts && buf generate

  setup-deps:
    desc: Setup protobuf dependencies using buf
    cmds:
      - echo "Setting up protobuf dependencies with buf..."
      - cd ../contracts && buf mod update

  clean:
    desc: Clean generated files
    cmds:
      - rm -rf internal/transport/grpc/pb
      - rm -rf api/swagger

  setup:
    desc: Full project setup
    deps: [install-tools, setup-deps, proto]

  run:
    desc: Run the order service
    cmds:
      - go run cmd/main.go